Repository prgrms-web-devcourse-final-project/WEB3_4_SsamMuDan_BE, pull requests merged in 2025-04, with the labels that each got.

#25 feat: #ET-3 TechBook 페이징 목록 조회 기능 구현
  src/main/java/ssammudan/cotree/domain/education/techbook/controller/TechBookController.java
  src/main/java/ssammudan/cotree/domain/education/techbook/dto/TechBookRequest.java
  src/main/java/ssammudan/cotree/domain/education/techbook/dto/TechBookResponse.java
  src/main/java/ssammudan/cotree/domain/education/techbook/service/TechBookService.java
  src/main/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceImpl.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryCustom.java
  src/main/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryImpl.java
  src/test/java/ssammudan/cotree/domain/education/techbook/controller/TechBookControllerTest.java
  src/test/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceTest.java
  src/test/java/ssammudan/cotree/model/education/level/repository/EducationLevelRepositoryTest.java
  src/test/java/ssammudan/cotree/model/education/supporter/DataJpaTestSupporter.java
  src/test/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryTest.java
Labels: enhancement

#31 [FEAT] : CD 구축을 위한 Dockerfile 및 배포 설정 추가
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#29 [FEAT] #RR-2 이력서 상세 조회 기능 구현
  src/main/java/ssammudan/cotree/CoTreeApplication.java
  src/main/java/ssammudan/cotree/domain/resume/controller/ResumeController.java
  src/main/java/ssammudan/cotree/domain/resume/dto/BasicInfoResponse.java
  src/main/java/ssammudan/cotree/domain/resume/dto/CareerInfoResponse.java
  src/main/java/ssammudan/cotree/domain/resume/dto/PortfolioInfoResponse.java
  src/main/java/ssammudan/cotree/domain/resume/dto/ResumeDetailResponse.java
  src/main/java/ssammudan/cotree/domain/resume/dto/query/BasicInfoQueryDto.java
  src/main/java/ssammudan/cotree/domain/resume/dto/query/TechStackInfo.java
  src/main/java/ssammudan/cotree/domain/resume/scheduler/ResumeScheduler.java
  src/main/java/ssammudan/cotree/domain/resume/service/ResumeService.java
  src/main/java/ssammudan/cotree/domain/resume/service/ResumeServiceImpl.java
  src/main/java/ssammudan/cotree/domain/resume/service/ResumeViewCountBuffer.java
  src/main/java/ssammudan/cotree/global/config/AsyncConfig.java
  src/main/java/ssammudan/cotree/global/response/ErrorCode.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/java/ssammudan/cotree/model/recruitment/career/career/repository/CareerRepository.java
  src/main/java/ssammudan/cotree/model/recruitment/portfolio/portfolio/repository/PortfolioRepository.java
  src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/ResumeRepository.java
  src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/ResumeRepositoryCustom.java
  src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/ResumeRepositoryImpl.java
Labels: enhancement

#46 [FIX] TechBook 테스트 관련 수정
  src/test/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceTest.java
  src/test/java/ssammudan/cotree/model/education/level/repository/EducationLevelRepositoryTest.java
  src/test/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryTest.java
Labels: bug

#47 [BUG] @RepeatedTest 제거, @Test 적용
  src/test/java/ssammudan/cotree/domain/education/techbook/controller/TechBookControllerTest.java
  src/test/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceTest.java
  src/test/java/ssammudan/cotree/model/education/level/repository/EducationLevelRepositoryTest.java
  src/test/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryTest.java
Labels: bug

#51 [FEAT] #RRDC-1, #CBDC-1 댓글 작성 기능 구현
  src/main/java/ssammudan/cotree/domain/comment/controller/CommentController.java
  src/main/java/ssammudan/cotree/domain/comment/dto/CommentRequest.java
  src/main/java/ssammudan/cotree/domain/comment/service/CommentService.java
  src/main/java/ssammudan/cotree/domain/comment/service/CommentServiceImpl.java
  src/main/java/ssammudan/cotree/domain/comment/type/CommentCategory.java
  src/main/java/ssammudan/cotree/domain/community/controller/CommunityController.java
  src/main/java/ssammudan/cotree/global/response/ErrorCode.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/java/ssammudan/cotree/model/common/comment/entity/Comment.java
Labels: enhancement

#61 [REFACTOR] : Security 인가 path 설정 및 누락 pord profile 설정 추가
  src/main/java/ssammudan/cotree/domain/comment/controller/CommentController.java
  src/main/java/ssammudan/cotree/domain/community/controller/CommunityController.java
  src/main/java/ssammudan/cotree/domain/project/controller/ProjectController.java
  src/main/java/ssammudan/cotree/domain/resume/controller/ResumeController.java
  src/main/java/ssammudan/cotree/domain/upload/controller/FileUploadController.java
  src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
  src/main/resources/config/prod/application-prod_auth.yml
  src/main/resources/config/prod/application-prod_server.yml
Labels: bug, enhancement

#74 [FEAT] #PTDL-2 #PTD-1 프로젝트 상세 조회
  src/main/java/ssammudan/cotree/domain/project/controller/ProjectController.java
  src/main/java/ssammudan/cotree/domain/project/dto/HotProjectResponse.java
  src/main/java/ssammudan/cotree/domain/project/dto/ProjectCreateRequest.java
  src/main/java/ssammudan/cotree/domain/project/dto/ProjectInfoResponse.java
  src/main/java/ssammudan/cotree/domain/project/service/ProjectService.java
  src/main/java/ssammudan/cotree/domain/project/service/ProjectServiceImpl.java
  src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
  src/main/java/ssammudan/cotree/global/response/ErrorCode.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/java/ssammudan/cotree/model/common/like/repository/LikeRepository.java
  src/main/java/ssammudan/cotree/model/project/devposition/repository/ProjectDevPositionRepository.java
  src/main/java/ssammudan/cotree/model/project/membership/entity/ProjectMembership.java
  src/main/java/ssammudan/cotree/model/project/membership/repository/ProjectMembershipRepository.java
  src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepository.java
  src/main/java/ssammudan/cotree/model/project/techstack/repository/ProjectTechStackRepository.java
Labels: enhancement

#70 [FEAT] #PTH-1 핫한 프로젝트 조회
  src/main/java/ssammudan/cotree/domain/project/service/ProjectServiceImpl.java
Labels: enhancement

#77 Feat/member/oauth/kakao login
  src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
  src/main/java/ssammudan/cotree/global/config/security/oauth/OAuth2UserService.java
  src/main/java/ssammudan/cotree/global/config/security/oauth/dto/KakaoResponse.java
  src/main/java/ssammudan/cotree/global/config/security/oauth/handler/OAuth2FailureHandler.java
  src/main/java/ssammudan/cotree/global/config/security/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/ssammudan/cotree/model/member/member/entity/Member.java
  src/main/java/ssammudan/cotree/model/member/oauth/entity/OAuth.java
  src/main/java/ssammudan/cotree/model/member/oauth/repository/OAuthRepository.java
  src/main/resources/config/dev/application-dev_auth.yml
  src/main/resources/config/prod/application-prod_auth.yml
  src/test/java/ssammudan/cotree/domain/member/controller/MemberControllerTest.java
  src/test/resources/config/test/application-test_auth.yml
Labels: enhancement

#84 [BUG] : S3 업로드 수정
  src/main/java/ssammudan/cotree/infra/s3/S3Uploader.java
  src/main/resources/config/dev/application-dev_server.yml
  src/main/resources/config/prod/application-prod_server.yml
Labels: bug

#76 [FEAT] : #CBDC-2, #RRDC-2 댓글 조회 기능 구현
  src/main/java/ssammudan/cotree/domain/comment/controller/CommentController.java
  src/main/java/ssammudan/cotree/domain/comment/dto/CommentResponse.java
  src/main/java/ssammudan/cotree/domain/comment/service/CommentService.java
  src/main/java/ssammudan/cotree/domain/comment/service/CommentServiceImpl.java
  src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
  src/main/java/ssammudan/cotree/global/response/ErrorCode.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/java/ssammudan/cotree/model/common/comment/entity/Comment.java
  src/main/java/ssammudan/cotree/model/common/comment/repository/CommentInfoProjection.java
  src/main/java/ssammudan/cotree/model/common/comment/repository/CommentRepository.java
  src/main/java/ssammudan/cotree/model/common/comment/repository/CommentRepositoryCustom.java
  src/main/java/ssammudan/cotree/model/common/comment/repository/CommentRepositoryImpl.java
  src/main/java/ssammudan/cotree/model/community/category/entity/CommunityCategory.java
  src/main/java/ssammudan/cotree/model/community/community/entity/Community.java
Labels: enhancement

#79 [FEAT] #MPTH-1, #PTH-1 HOT한 프로젝트 구현(메인페이지, 프로젝트 페이지 별도)
  src/main/java/ssammudan/cotree/domain/project/controller/ProjectController.java
  src/main/java/ssammudan/cotree/domain/project/service/ProjectService.java
  src/main/java/ssammudan/cotree/domain/project/service/ProjectServiceImpl.java
  src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
  src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepository.java
Labels: enhancement

#91 [BUG] TechBook, 리뷰(수강평) 정렬 조건 누락 수정 등
  src/main/java/ssammudan/cotree/domain/education/techbook/controller/TechBookController.java
  src/main/java/ssammudan/cotree/domain/education/techbook/dto/TechBookResponse.java
  src/main/java/ssammudan/cotree/domain/education/type/SearchEducationSort.java
  src/main/java/ssammudan/cotree/domain/review/controller/TechEducationReviewController.java
  src/main/java/ssammudan/cotree/domain/review/service/TechEducationReviewServiceImpl.java
  src/main/java/ssammudan/cotree/domain/review/type/SearchReviewSort.java
  src/main/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryImpl.java
  src/main/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepository.java
  src/main/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryCustom.java
  src/main/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryImpl.java
  src/test/java/ssammudan/cotree/domain/education/techbook/controller/TechBookControllerTest.java
  src/test/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceTest.java
  src/test/java/ssammudan/cotree/domain/review/controller/TechEducationReviewControllerTest.java
  src/test/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryTest.java
  src/test/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryTest.java
Labels: bug, enhancement

#95 [FEAT] #MI1, #MI2 회원 정보 제공, 수정 기능 구현
  src/main/java/ssammudan/cotree/domain/member/controller/MemberController.java
  src/main/java/ssammudan/cotree/domain/member/dto/info/MemberInfoRequest.java
  src/main/java/ssammudan/cotree/domain/member/dto/info/MemberInfoResponse.java
  src/main/java/ssammudan/cotree/domain/member/dto/signup/MemberSignupRequest.java
  src/main/java/ssammudan/cotree/domain/member/service/MemberService.java
  src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/java/ssammudan/cotree/model/member/member/entity/Member.java
  src/main/java/ssammudan/cotree/model/member/member/entity/MemberFactory.java
  src/test/java/ssammudan/cotree/domain/member/service/MemberServiceTest.java
Labels: enhancement

#103 [Bugfix] : 회원가입 시 중복 회원가입 버그 수정
  src/main/java/ssammudan/cotree/domain/member/controller/MemberController.java
  src/main/java/ssammudan/cotree/domain/member/dto/signup/MemberSignupRequest.java
  src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java
  src/main/resources/db/migration/V2.1__add_unique_constraints_to_member.sql
  src/main/resources/db/seed/dev/R__B_insert_member_seed.sql
Labels: bug

#88 [FEAT] #PTDV-1 Redis를 활용한 조회수 업데이트 방식 구현 및 성능 최적화
  src/main/java/ssammudan/cotree/domain/project/redis/RedisViewCountScheduler.java
  src/main/java/ssammudan/cotree/domain/project/service/ProjectServiceImpl.java
  src/main/java/ssammudan/cotree/domain/project/service/ProjectViewService.java
  src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepository.java
Labels: enhancement

#117 [FEAT] #PTDS-1 프로젝트 모집 상태 변경
  src/main/java/ssammudan/cotree/domain/project/controller/ProjectController.java
  src/main/java/ssammudan/cotree/domain/project/service/ProjectService.java
  src/main/java/ssammudan/cotree/domain/project/service/ProjectServiceImpl.java
  src/main/java/ssammudan/cotree/global/response/ErrorCode.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/java/ssammudan/cotree/model/project/project/entity/Project.java
Labels: enhancement

#121 [FIX] techstack image url들 s3 이미지로 변경
  src/main/resources/db/seed/dev/R__A_insert_seed.sql
  src/main/resources/db/seed/prod/R__A_insert_seed.sql
Labels: bug

#127 [FEAT] : #CE-1 교육 카테고리 검색
  src/main/java/ssammudan/cotree/domain/category/controller/CategoryController.java
  src/main/java/ssammudan/cotree/domain/category/dto/EducationCategoryResponse.java
  src/main/java/ssammudan/cotree/domain/category/service/CategoryService.java
  src/main/java/ssammudan/cotree/domain/category/service/CategoryServiceImpl.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
Labels: enhancement

#119 [FEAT] : 이메일 인증 기능 구현
  build.gradle
  src/main/java/ssammudan/cotree/domain/email/controller/EmailController.java
  src/main/java/ssammudan/cotree/domain/email/dto/EmailRequest.java
  src/main/java/ssammudan/cotree/domain/email/dto/EmailVerifyRequest.java
  src/main/java/ssammudan/cotree/domain/email/service/EmailService.java
  src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java
  src/main/java/ssammudan/cotree/domain/phone/service/SmsService.java
  src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
  src/main/java/ssammudan/cotree/global/config/security/jwt/RefreshTokenService.java
  src/main/java/ssammudan/cotree/global/response/ErrorCode.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/resources/config/dev/application-dev_auth.yml
  src/main/resources/config/prod/application-prod_auth.yml
  src/test/java/ssammudan/cotree/domain/category/controller/CategoryControllerTest.java
  src/test/java/ssammudan/cotree/domain/member/service/MemberServiceTest.java
  src/test/java/ssammudan/cotree/domain/resume/service/ResumeServiceImplTest.java
  src/test/java/ssammudan/cotree/integration/SpringBootTestSupporter.java
Labels: enhancement

#146 [Bug] 회원가입 오류
  src/main/java/ssammudan/cotree/domain/email/service/EmailService.java
  src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java
  src/main/java/ssammudan/cotree/domain/phone/service/SmsService.java
Labels: bug

#141 [REFACTOR] Community Board 조회 (리스트, 단건) 시, 프로필 이미지 추가 return
  src/main/java/ssammudan/cotree/domain/community/dto/CommunityResponse.java
  src/main/java/ssammudan/cotree/domain/community/service/CommunityServiceImpl.java
  src/main/java/ssammudan/cotree/model/community/community/repository/CommunityRepositoryImpl.java
Labels: enhancement

#135 [FEAT] TossPayments API를 활용한 결제 기능 구현
  build.gradle
  src/main/java/ssammudan/cotree/domain/order/facade/OrderFacade.java
  src/main/java/ssammudan/cotree/domain/order/service/OrderCategoryService.java
  src/main/java/ssammudan/cotree/domain/order/service/OrderCategoryServiceImpl.java
  src/main/java/ssammudan/cotree/domain/order/service/OrderHistoryService.java
  src/main/java/ssammudan/cotree/domain/order/service/OrderHistoryServiceImpl.java
  src/main/java/ssammudan/cotree/domain/payment/controller/PaymentController.java
  src/main/java/ssammudan/cotree/domain/payment/dto/PaymentRequest.java
  src/main/java/ssammudan/cotree/domain/payment/dto/PaymentResponse.java
  src/main/java/ssammudan/cotree/domain/payment/dto/PrePaymentValue.java
  src/main/java/ssammudan/cotree/domain/payment/dto/TossPaymentRequest.java
  src/main/java/ssammudan/cotree/domain/payment/dto/TossPaymentResponse.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentService.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentServiceImpl.java
  src/main/java/ssammudan/cotree/domain/review/controller/TechEducationReviewController.java
  src/main/java/ssammudan/cotree/domain/review/dto/TechEducationReviewRequest.java
  src/main/java/ssammudan/cotree/domain/review/dto/TechEducationReviewResponse.java
  src/main/java/ssammudan/cotree/domain/review/service/TechEducationReviewServiceImpl.java
  src/main/java/ssammudan/cotree/global/config/AppConfig.java
  src/main/java/ssammudan/cotree/global/config/WebConfig.java
  src/main/java/ssammudan/cotree/global/response/ErrorCode.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/java/ssammudan/cotree/infra/payment/PaymentClient.java
  src/main/java/ssammudan/cotree/infra/payment/constant/PaymentConstant.java
  src/main/java/ssammudan/cotree/infra/payment/dto/ApiPaymentRequest.java
  src/main/java/ssammudan/cotree/infra/payment/dto/ApiPaymentResponse.java
  src/main/java/ssammudan/cotree/infra/payment/toss/TossPaymentClient.java
  src/main/java/ssammudan/cotree/infra/payment/toss/TossPaymentHttpClient.java
  src/main/java/ssammudan/cotree/infra/redis/RedisConfig.java
  src/main/java/ssammudan/cotree/model/payment/order/history/entity/OrderHistory.java
  src/main/java/ssammudan/cotree/model/payment/order/history/repository/OrderHistoryRepository.java
  src/main/java/ssammudan/cotree/model/payment/order/type/PaymentStatus.java
  src/main/java/ssammudan/cotree/model/review/reviewtype/type/EducationType.java
  src/main/resources/db/migration/V2.5__add_column_order_history.sql
  src/test/java/ssammudan/cotree/domain/review/controller/TechEducationReviewControllerTest.java
  src/test/java/ssammudan/cotree/domain/review/service/TechEducationReviewServiceTest.java
  src/test/resources/config/test/application-test_auth.yml
Labels: enhancement

#154 [REFACTOR] 채용 지원 조회 반환값에 viewcount 누락
  src/main/java/ssammudan/cotree/domain/resume/dto/ResumeResponse.java
  src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/ResumeRepositoryQueryDslImpl.java
  src/main/resources/db/seed/dev/R__I_insert_resume_seed.sql
  src/main/resources/db/seed/dev/R__J_insert_resume_position_seed.sql
Labels: enhancement

#157 [BUG] TossPayments API 키 설정 추가
  src/main/java/ssammudan/cotree/infra/payment/toss/TossPaymentHttpClient.java
  src/main/resources/config/dev/application-dev_auth.yml
  src/main/resources/config/prod/application-prod_auth.yml
  src/test/resources/config/test/application-test_auth.yml
Labels: bug

#162 [FEAT] #PTDA-1 프로젝트 참가 신청
  src/main/java/ssammudan/cotree/domain/project/controller/ProjectController.java
  src/main/java/ssammudan/cotree/domain/project/service/ProjectService.java
  src/main/java/ssammudan/cotree/domain/project/service/ProjectServiceImpl.java
  src/main/java/ssammudan/cotree/global/response/ErrorCode.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/java/ssammudan/cotree/model/project/membership/entity/ProjectMembership.java
  src/main/java/ssammudan/cotree/model/project/membership/repository/ProjectMembershipRepository.java
Labels: enhancement

#160 [Bug] : 회원 업데이트 버그 수정
  src/main/java/ssammudan/cotree/domain/member/controller/MemberController.java
  src/main/java/ssammudan/cotree/domain/member/dto/info/MemberInfoResponse.java
  src/main/java/ssammudan/cotree/domain/member/service/MemberService.java
  src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java
  src/main/java/ssammudan/cotree/model/member/member/entity/Member.java
Labels: bug

#172 [BUG] CORS 허용 메서드에 PATCH 추가
  src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
Labels: bug

#159 [FEAT] #IGC-1 Gemini API 기반 GitHub Actions 리뷰 자동화 도입
  .github/workflows/gemini_code_review.yml
Labels: enhancement

#170 [Feat] : #MRP-1 비밀번호 변경 구현
  src/main/java/ssammudan/cotree/domain/member/controller/MemberController.java
  src/main/java/ssammudan/cotree/domain/member/dto/signup/MemberSignupRequest.java
  src/main/java/ssammudan/cotree/domain/member/service/MemberService.java
  src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/java/ssammudan/cotree/model/member/member/entity/Member.java
  src/main/java/ssammudan/cotree/model/member/member/type/MemberRole.java
  src/test/java/ssammudan/cotree/domain/member/service/MemberServiceTest.java
  src/test/java/ssammudan/cotree/integration/factory/MemberDataFactory.java
Labels: enhancement

#166 [FEAT] #PTDM-1 프로젝트 참가자 전체 목록 조회
  src/main/java/ssammudan/cotree/domain/project/common/helper/ProjectHelper.java
  src/main/java/ssammudan/cotree/domain/project/membership/dto/MembershipResponse.java
  src/main/java/ssammudan/cotree/domain/project/membership/service/MembershipService.java
  src/main/java/ssammudan/cotree/domain/project/membership/service/MembershipServiceImpl.java
  src/main/java/ssammudan/cotree/domain/project/project/controller/ProjectController.java
  src/main/java/ssammudan/cotree/domain/project/project/dto/ProjectCreateRequest.java
  src/main/java/ssammudan/cotree/domain/project/project/dto/ProjectCreateResponse.java
  src/main/java/ssammudan/cotree/domain/project/project/dto/ProjectInfoResponse.java
  src/main/java/ssammudan/cotree/domain/project/project/dto/ProjectListResponse.java
  src/main/java/ssammudan/cotree/domain/project/project/scheduler/ProjectViewCountScheduler.java
  src/main/java/ssammudan/cotree/domain/project/project/service/ProjectService.java
  src/main/java/ssammudan/cotree/domain/project/project/service/ProjectServiceImpl.java
  src/main/java/ssammudan/cotree/domain/project/project/service/ProjectViewService.java
  src/main/java/ssammudan/cotree/global/response/ErrorCode.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/java/ssammudan/cotree/model/project/membership/repository/ProjectMembershipRepository.java
  src/main/java/ssammudan/cotree/model/project/membership/repository/ProjectMembershipRepositoryCustom.java
  src/main/java/ssammudan/cotree/model/project/membership/repository/ProjectMembershipRepositoryImpl.java
  src/main/java/ssammudan/cotree/model/project/membership/type/ProjectMembershipStatus.java
  src/main/java/ssammudan/cotree/model/project/project/entity/Project.java
  src/main/java/ssammudan/cotree/model/project/project/helper/ProjectQueryHelper.java
  src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepositoryCustom.java
  src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepositoryImpl.java
Labels: enhancement

#177 [FEAT] : 이메일 전송 비동기 처리
  src/main/java/ssammudan/cotree/domain/email/service/EmailService.java
Labels: enhancement

#174 [FEAT] #PTDD-1 프로젝트 직무별 모집 인원 수정
  src/main/java/ssammudan/cotree/domain/project/project/controller/ProjectController.java
  src/main/java/ssammudan/cotree/domain/project/project/dto/ProjectDevPositionResponse.java
  src/main/java/ssammudan/cotree/domain/project/project/dto/ProjectInfoResponse.java
  src/main/java/ssammudan/cotree/domain/project/project/dto/UpdateProjectPositionRequest.java
  src/main/java/ssammudan/cotree/domain/project/project/service/ProjectService.java
  src/main/java/ssammudan/cotree/domain/project/project/service/ProjectServiceImpl.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/java/ssammudan/cotree/model/project/devposition/entity/ProjectDevPosition.java
  src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepositoryCustom.java
  src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepositoryImpl.java
Labels: enhancement

#187 [FEAT] 프론트엔드 서버 URL CORS 허용 경로 추가
  src/main/java/ssammudan/cotree/domain/project/project/service/ProjectServiceImpl.java
  src/main/java/ssammudan/cotree/global/config/FrontendConfig.java
  src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
  src/main/java/ssammudan/cotree/global/config/security/oauth/handler/OAuth2FailureHandler.java
  src/main/java/ssammudan/cotree/global/config/security/oauth/handler/OAuth2SuccessHandler.java
Labels: enhancement

#185 [FEAT] : 회원 조회 데이터에 profileImgUrl 추가
  src/main/java/ssammudan/cotree/domain/member/dto/info/MemberInfoResponse.java
Labels: enhancement

#193 [BUG] : Redis 저장 결제 정보 시간 단위 수정
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentServiceImpl.java
Labels: bug

#194 Main merge
  src/main/java/ssammudan/cotree/domain/member/dto/info/MemberInfoResponse.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentServiceImpl.java
Labels: bug

#197 [BUG] 결제 로직 중 Redis 저장 데이터 역직렬화 에러 등 수정
  src/main/java/ssammudan/cotree/domain/order/facade/OrderFacade.java
  src/main/java/ssammudan/cotree/domain/order/service/OrderHistoryService.java
  src/main/java/ssammudan/cotree/domain/order/service/OrderHistoryServiceImpl.java
  src/main/java/ssammudan/cotree/domain/payment/controller/PaymentController.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentService.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentServiceImpl.java
Labels: bug

#200 Main merge
  src/main/java/ssammudan/cotree/domain/order/facade/OrderFacade.java
  src/main/java/ssammudan/cotree/domain/order/service/OrderHistoryService.java
  src/main/java/ssammudan/cotree/domain/order/service/OrderHistoryServiceImpl.java
  src/main/java/ssammudan/cotree/domain/payment/controller/PaymentController.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentService.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentServiceImpl.java
Labels: bug

#198 [FEAT] #CBL-1 커뮤니티 좋아요 글 목록 조회
  src/main/java/ssammudan/cotree/domain/community/controller/CommunityController.java
  src/main/java/ssammudan/cotree/domain/community/dto/CommunityResponse.java
  src/main/java/ssammudan/cotree/domain/community/service/CommunityService.java
  src/main/java/ssammudan/cotree/domain/community/service/CommunityServiceImpl.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/java/ssammudan/cotree/model/common/like/repository/LikeRepositoryCustom.java
  src/main/java/ssammudan/cotree/model/common/like/repository/LikeRepositoryImpl.java
Labels: enhancement

#204 refactor: Transaction 예외처리 실패 해결
  src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java
Labels: bug

#202 [FEAT] #ETL-2 TechTube 좋아요 글 목록 조회
  src/main/java/ssammudan/cotree/domain/education/techtube/controller/TechTubeController.java
  src/main/java/ssammudan/cotree/domain/education/techtube/dto/TechTubeResponse.java
  src/main/java/ssammudan/cotree/domain/education/techtube/service/TechTubeService.java
  src/main/java/ssammudan/cotree/domain/education/techtube/service/TechTubeServiceImpl.java
  src/main/java/ssammudan/cotree/global/response/SuccessCode.java
  src/main/java/ssammudan/cotree/model/common/like/repository/LikeRepositoryCustom.java
  src/main/java/ssammudan/cotree/model/common/like/repository/LikeRepositoryImpl.java
Labels: enhancement

#196 [TEST] 커뮤니티 도메인 테스트 코드 작성
  src/main/java/ssammudan/cotree/domain/community/dto/CommunityRequest.java
  src/main/java/ssammudan/cotree/domain/community/dto/CommunityResponse.java
  src/main/java/ssammudan/cotree/domain/community/service/CommunityService.java
  src/main/java/ssammudan/cotree/domain/community/service/CommunityServiceImpl.java
  src/main/java/ssammudan/cotree/model/common/comment/repository/CommentRepository.java
  src/main/java/ssammudan/cotree/model/common/like/repository/LikeRepository.java
  src/main/java/ssammudan/cotree/model/community/category/repository/CommunityCategoryRepository.java
  src/main/java/ssammudan/cotree/model/community/community/repository/CommunityRepository.java
  src/main/java/ssammudan/cotree/model/community/community/repository/CommunityRepositoryCustom.java
  src/main/java/ssammudan/cotree/model/community/community/repository/CommunityRepositoryImpl.java
  src/test/java/ssammudan/cotree/domain/community/controller/CommunityControllerTest.java
  src/test/java/ssammudan/cotree/domain/community/dto/CommunityRequestTest.java
  src/test/java/ssammudan/cotree/domain/community/service/CommunityServiceImplTest.java
  src/test/java/ssammudan/cotree/integration/SpringBootTestSupporter.java
  src/test/java/ssammudan/cotree/integration/factory/CommentDataFactory.java
  src/test/java/ssammudan/cotree/integration/factory/CommunityDataFactory.java
  src/test/java/ssammudan/cotree/integration/factory/LikeDataFactory.java
  src/test/java/ssammudan/cotree/integration/factory/MemberDataFactory.java
  src/test/java/ssammudan/cotree/integration/security/WithCustomUser.java
  src/test/java/ssammudan/cotree/integration/security/WithCustomUserSecurityContextFactory.java
  src/test/java/ssammudan/cotree/model/community/category/repository/CommunityCategoryRepositoryTest.java
  src/test/java/ssammudan/cotree/model/community/category/repository/CommunityRepositoryTest.java
Labels: enhancement

#209 [BUG] TechBook 조회 에러 수정 등
  src/main/java/ssammudan/cotree/domain/education/techbook/controller/TechBookController.java
  src/main/java/ssammudan/cotree/domain/education/techbook/dto/TechBookRequest.java
  src/main/java/ssammudan/cotree/domain/education/techbook/dto/TechBookResponse.java
  src/main/java/ssammudan/cotree/domain/education/techbook/service/TechBookService.java
  src/main/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceImpl.java
  src/main/java/ssammudan/cotree/domain/order/facade/OrderFacade.java
  src/main/java/ssammudan/cotree/domain/payment/controller/PaymentController.java
  src/main/java/ssammudan/cotree/domain/payment/dto/PaymentResponse.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentService.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentServiceImpl.java
  src/main/java/ssammudan/cotree/domain/review/controller/TechEducationReviewController.java
  src/main/java/ssammudan/cotree/domain/review/dto/TechEducationReviewRequest.java
  src/main/java/ssammudan/cotree/domain/review/dto/TechEducationReviewResponse.java
  src/main/java/ssammudan/cotree/domain/review/service/TechEducationReviewService.java
  src/main/java/ssammudan/cotree/domain/review/service/TechEducationReviewServiceImpl.java
  src/main/java/ssammudan/cotree/global/response/PageResponse.java
  src/main/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryCustom.java
  src/main/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryImpl.java
  src/main/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryCustom.java
  src/main/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryImpl.java
  src/test/java/ssammudan/cotree/domain/education/techbook/controller/TechBookControllerTest.java
  src/test/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceTest.java
  src/test/java/ssammudan/cotree/domain/review/controller/TechEducationReviewControllerTest.java
  src/test/java/ssammudan/cotree/domain/review/service/TechEducationReviewServiceTest.java
  src/test/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryTest.java
Labels: bug

#210 Main merge
  src/main/java/ssammudan/cotree/domain/education/techbook/controller/TechBookController.java
  src/main/java/ssammudan/cotree/domain/education/techbook/dto/TechBookRequest.java
  src/main/java/ssammudan/cotree/domain/education/techbook/dto/TechBookResponse.java
  src/main/java/ssammudan/cotree/domain/education/techbook/service/TechBookService.java
  src/main/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceImpl.java
  src/main/java/ssammudan/cotree/domain/order/facade/OrderFacade.java
  src/main/java/ssammudan/cotree/domain/payment/controller/PaymentController.java
  src/main/java/ssammudan/cotree/domain/payment/dto/PaymentResponse.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentService.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentServiceImpl.java
  src/main/java/ssammudan/cotree/domain/review/controller/TechEducationReviewController.java
  src/main/java/ssammudan/cotree/domain/review/dto/TechEducationReviewRequest.java
  src/main/java/ssammudan/cotree/domain/review/dto/TechEducationReviewResponse.java
  src/main/java/ssammudan/cotree/domain/review/service/TechEducationReviewService.java
  src/main/java/ssammudan/cotree/domain/review/service/TechEducationReviewServiceImpl.java
  src/main/java/ssammudan/cotree/global/response/PageResponse.java
  src/main/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryCustom.java
  src/main/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryImpl.java
  src/main/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryCustom.java
  src/main/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryImpl.java
  src/test/java/ssammudan/cotree/domain/education/techbook/controller/TechBookControllerTest.java
  src/test/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceTest.java
  src/test/java/ssammudan/cotree/domain/review/controller/TechEducationReviewControllerTest.java
  src/test/java/ssammudan/cotree/domain/review/service/TechEducationReviewServiceTest.java
  src/test/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryTest.java
Labels: bug

#215 [BUG] 아이디 찾기 security 설정 누락
  src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
Labels: bug

#223 [FIX] 좋아요 누른 프로젝트 조회
  src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepositoryImpl.java
Labels: bug

#228 [FIX] : 비밀번호 변경 수정
  src/main/java/ssammudan/cotree/domain/member/controller/MemberController.java
  src/main/java/ssammudan/cotree/domain/member/dto/update/MemberPasswordRequest.java
  src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
Labels: bug

#231 [FEAT]: CustomUserDetailsService.loadUserByRefreshToken 구현
  src/main/java/ssammudan/cotree/global/config/security/filter/JwtAuthenticationFilter.java
  src/main/java/ssammudan/cotree/global/config/security/user/CustomUserDetailsService.java
Labels: bug

#234 [FEAT] 결제 응답 정보에 리다이렉트용 데이터 필드 추가
  src/main/java/ssammudan/cotree/domain/order/facade/OrderFacade.java
  src/main/java/ssammudan/cotree/domain/payment/dto/PaymentResponse.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentService.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentServiceImpl.java
Labels: enhancement

#235 Main merge
  src/main/java/ssammudan/cotree/domain/member/controller/MemberController.java
  src/main/java/ssammudan/cotree/domain/member/dto/update/MemberPasswordRequest.java
  src/main/java/ssammudan/cotree/domain/order/facade/OrderFacade.java
  src/main/java/ssammudan/cotree/domain/payment/dto/PaymentResponse.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentService.java
  src/main/java/ssammudan/cotree/domain/payment/service/PaymentServiceImpl.java
  src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
  src/main/java/ssammudan/cotree/global/config/security/filter/JwtAuthenticationFilter.java
  src/main/java/ssammudan/cotree/global/config/security/user/CustomUserDetailsService.java
Labels: enhancement

#237 [BUG] 비밀번호 변경에 시큐리티 인증객체 의존성 제거
  src/main/java/ssammudan/cotree/domain/member/controller/MemberController.java
  src/main/java/ssammudan/cotree/domain/member/dto/update/MemberPasswordRequest.java
  src/main/java/ssammudan/cotree/domain/member/service/MemberService.java
  src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java
Labels: bug

#233 [TEST] SMS 서비스 및 구매목록 조회 테스트 코드 작성
  src/main/java/ssammudan/cotree/global/response/ErrorCode.java
  src/main/java/ssammudan/cotree/infra/sms/CoolSmsMessageSender.java
  src/main/java/ssammudan/cotree/infra/sms/MessageSender.java
  src/main/java/ssammudan/cotree/infra/sms/SmsService.java
  src/main/java/ssammudan/cotree/model/recruitment/career/career/entity/Career.java
  src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/ResumeRepositoryQueryDslImpl.java
  src/test/java/ssammudan/cotree/domain/category/controller/CategoryControllerTest.java
  src/test/java/ssammudan/cotree/domain/member/service/MemberServiceTest.java
  src/test/java/ssammudan/cotree/infra/sms/SmsServiceTest.java
  src/test/java/ssammudan/cotree/integration/SpringBootTestSupporter.java
Labels: enhancement

#241 [REFACTOR] 이력서 조회 쿼리 중간 DTO 생성
  src/main/java/ssammudan/cotree/domain/resume/dto/ResumeResponse.java
  src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/ResumeRepositoryQueryDslImpl.java
  src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/dto/ResumeBasicInfoDto.java
  src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/dto/ResumePositionDto.java
  src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/dto/ResumeTechStackDto.java
Labels: enhancement

#244 [FEAT] : 데이터베이스 분리
  .gitignore
  build.gradle
  docker/database/db-docker-compose.yml
  docker/database/mysql/init.sh
  docker/monitoring/monitoring-docker-compose.yml
  docker/monitoring/prometheus.yml
  src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
  src/main/resources/config/dev/application-dev_server.yml
  terraform/main.tf
Labels: documentation
